=== RocalL/webApp/src/database/candidature.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="candidatures">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="candidature" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:byte" name="idCandidature" />
							<xs:element type="xs:string" name="dateCandidature" />
							<xs:element name="identiteCandidat">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="nom" />
										<xs:element type="xs:string" name="prenom" />
										<xs:element type="xs:int" name="tel" />
										<xs:element type="xs:string" name="mail" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="structure">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="raisonSocial" />
										<xs:element type="xs:long" name="siret" />
										<xs:element type="xs:byte" name="ca" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="repProjet">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:byte" name="delais" />
										<xs:element type="xs:anyURI" name="devis" />
										<xs:element type="xs:anyURI" name="liens" />
										<xs:element name="fichiers">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:anyURI" name="fichier"
														maxOccurs="unbounded" minOccurs="0" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:byte" name="idProjet" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== RocalL/webApp/src/candidature.xml
<?xml version="1.0" encoding="UTF-8"?>
<candidature
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="candidature.xsd">
  <idCandidature>1</idCandidature>
  <dateCandidature>12/04/2018</dateCandidature>
  <identiteCandidat>
    <nom>Durand</nom>
    <prenom>Jacques-yves</prenom>
    <tel>0612345678</tel>
    <mail>d.jacky@iopmail.com</mail>
  </identiteCandidat>
  <structure>
    <raisonSocial>Jacky la bidouille</raisonSocial>
    <siret>73282932000074</siret>
    <ca>20</ca>
  </structure>
  <repProjet>
    <delais>15</delais>
    <devis>http://monServeur/devis/1</devis>
    <liens>http://www.JackyBidouille.com</liens>
    <fichiers>
      <fichier>http://monServeur/fichiers/1-1</fichier>
      <fichier>http://monServeur/fichiers/1-2</fichier>
    </fichiers>
    <idProjet>1</idProjet>
  </repProjet>
</candidature>
